#!/usr/bin/env python3
"""Release pipeline client release pipeline rehearsal.

Drives the REAL release tooling against a fully synthetic environment in a temp
directory:

  * `client/tools/release/package_client.py` packages a fake build tree,
  * `client/tools/release/gen_manifest.py` signs the manifest with a throwaway
    Ed25519 key generated by the OpenSSL CLI,
  * `server/deploy/tls/make_cert.sh` generates the self-signed release
    certificate and the SPKI pin,
  * `server/deploy/hpmmo_status.py` serves the status document and the release
    root over HTTPS with that certificate, on a loopback port.

Nothing here touches the live box, the real keys, or the repository: every
artifact, key, certificate, channel pointer and process lives under a temp root
that is removed at the end.

Rehearsed exit checks ("Exit checks" + the release contract):

  1. deterministic packaging: the same build tree produces the same zip bytes
  2. deterministic manifest: the same inputs and a pinned --published-at
     produce the same manifest bytes, and the same signature
  3. the signature verifies over the exact manifest bytes; the .sig file is one
     line of base64 holding a raw 64-byte signature; the key id travels in the
     sidecar and equals the pinned public key's SPKI sha256
  4. a tampered manifest fails verification; the right manifest under a wrong
     key (or an unexpected key id) fails verification
  5. a tampered artifact fails its recorded hash
  6. the package contains no user data, no editor cache and no secret - and the
     packager refuses a build tree that does (by path and by content)
  7. the version fields gate correctly: a server-only bump (new server_version /
     schema_version against an identical client artifact) requires NO client
     download, while a client bump, a raised protocol floor, a raised launcher
     minimum and a content mismatch behave as documented
  8. HTTPS: the pinned certificate is served, /releases/ serves the manifest
     (whose signature verifies over the served bytes) and the artifact, HEAD
     reports the size, traversal and dotfile requests are refused, and a public
     bind without TLS is refused
  9. the contracted files exist, the workflow carries the required controls, and
     no key material is committed beside the tooling

Usage:
  python server/tests/release_pipeline_test.py [--case NAME] [--keep] [--verbose]

Set HPMMO_CLIENT_REPO to point at another checkout of the client repository,
HPMMO_OPENSSL to use a different openssl binary.

Prints one PASS/FAIL line per check and finishes with
    RELEASE RESULT: N checks, M failures
Exit code is 0 when there are no failures (1 otherwise, 2 when the tooling
cannot run at all).
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import http.client
import json
import os
import re
import shutil
import socket
import ssl
import subprocess
import sys
import tempfile
import time
import zipfile

HERE = os.path.dirname(os.path.abspath(__file__))
SERVER = os.path.dirname(HERE)
WORKSPACE = os.path.dirname(SERVER)
CLIENT = os.environ.get("HPMMO_CLIENT_REPO") or os.path.join(WORKSPACE, "client")
BASH: "str | None" = None  # resolved in main(), see find_bash()
TOOLS = os.path.join(CLIENT, "tools", "release")
PACKAGER = os.path.join(TOOLS, "package_client.py")
MANIFEST_TOOL = os.path.join(TOOLS, "gen_manifest.py")
MAKE_CERT = os.path.join(SERVER, "deploy", "tls", "make_cert.sh")
STATUS_SERVICE = os.path.join(SERVER, "deploy", "hpmmo_status.py")
WORKFLOW = os.path.join(CLIENT, ".github", "workflows", "client-release.yml")
CONTRACT_DOC = os.path.join(SERVER, "docs", "release-contract.md")

sys.path.insert(0, TOOLS)
try:
    import release_common as rc  # noqa: E402
except ImportError:  # pragma: no cover - reported as a failed check
    rc = None  # type: ignore[assignment]

CLIENT_VERSION = "0.7.0"
CONTENT_VERSION = "2026.10.04-1"
PLATFORM = "windows-x86_64"
BASE_URL = "https://213.250.145.75:8443/releases"
PUBLISHED_AT = "2026-10-04T00:00:00Z"
CERT_DAYS = 825

checks = 0
failures: list[str] = []
VERBOSE = False
KEEP = False
_TEMP_ROOT = ""
_FIXTURE: dict = {}


def check(condition, message: str) -> bool:
    global checks
    checks += 1
    if condition:
        print("PASS: " + message)
        return True
    failures.append(message)
    print("FAIL: " + message)
    return False


def note(message: str) -> None:
    if VERBOSE:
        print("      " + message)


def say(message: str) -> None:
    print("\n--- %s ---" % message)


# --- helpers -----------------------------------------------------------------

def openssl(*args: str, stdin: bytes | None = None) -> subprocess.CompletedProcess:
    return subprocess.run([os.environ.get("HPMMO_OPENSSL", "openssl")] + list(args),
                          input=stdin, capture_output=True)


def find_bash() -> str | None:
    """A real POSIX bash. On Windows `bash` on PATH is the WSL launcher, which
    cannot run these scripts; deploy_rehearsal.py resolves it the same way."""
    override = os.environ.get("HPMMO_BASH")
    if override:
        return override if os.path.exists(override) else None
    if os.name == "nt":
        for candidate in (r"C:\Program Files\Git\usr\bin\bash.exe",
                          r"C:\Program Files\Git\bin\bash.exe",
                          r"C:\Program Files (x86)\Git\usr\bin\bash.exe"):
            if os.path.isfile(candidate):
                return candidate
        return None
    found = shutil.which("bash")
    return found if found else None


def looks_like_secret(path: str) -> str:
    """A stricter, value-based secret scan than `release_common.content_refusal`
    (which also matches the *patterns themselves* in the tool's own source)."""
    try:
        with open(path, "rb") as handle:
            data = handle.read(512 * 1024)
    except OSError:
        return ""
    text = data.decode("utf-8", "replace")
    if re.search(r"-----BEGIN [A-Z ]*PRIVATE KEY-----[ \t]*\r?\n[A-Za-z0-9+/=]{40,}", text):
        return "a PEM private key block"
    for pattern in (r"HPMMO_SERVICE_TOKEN=\S{8,}", r"HPMMO_DB_PASSWORD=\S{6,}",
                    r"PGPASSWORD=\S{6,}", r"DATABASE_URL=postgres(ql)?://",
                    r"postgres(ql)?://[^\s:@/]+:[^\s@/]+@"):
        if re.search(pattern, text):
            return "a credential value matching %s" % pattern
    return ""


def python_tool(script: str, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run([sys.executable, script] + list(args), capture_output=True, text=True)


def temp_dir(prefix: str) -> str:
    return tempfile.mkdtemp(prefix=prefix, dir=_TEMP_ROOT)


def make_keypair(directory: str, name: str = "release") -> tuple[str, str]:
    key = os.path.join(directory, name + ".key.pem")
    pub = os.path.join(directory, name + ".pub.pem")
    result = openssl("genpkey", "-algorithm", "ed25519", "-out", key)
    assert result.returncode == 0, result.stderr
    result = openssl("pkey", "-in", key, "-pubout", "-out", pub)
    assert result.returncode == 0, result.stderr
    return key, pub


def spki_pin(public_key_path: str) -> str:
    """SPKI sha256 of a *public key* file (the manifest-side pin)."""
    result = openssl("pkey", "-pubin", "-in", public_key_path, "-pubout", "-outform", "DER")
    assert result.returncode == 0, result.stderr
    return hashlib.sha256(result.stdout).hexdigest()


def spki_pin_of_certificate(cert_path: str) -> str:
    """SPKI sha256 of a *certificate* (the TLS-side pin)."""
    public_key = openssl("x509", "-in", cert_path, "-noout", "-pubkey")
    assert public_key.returncode == 0, public_key.stderr
    result = openssl("pkey", "-pubin", "-outform", "DER", stdin=public_key.stdout)
    assert result.returncode == 0, result.stderr
    return hashlib.sha256(result.stdout).hexdigest()


def make_build_tree(parent: str) -> str:
    """A minimal but realistic build directory: an exported game payload and a
    launcher with its branding assets."""
    build = os.path.join(parent, "build")
    os.makedirs(os.path.join(build, "client"))
    os.makedirs(os.path.join(build, "launcher", "assets"))
    with open(os.path.join(build, "client", "hpmmo.exe"), "wb") as handle:
        handle.write(b"MZ" + b"\x00" * 512 + b"fake exported game executable\n")
    with open(os.path.join(build, "client", "hpmmo.pck"), "wb") as handle:
        handle.write(b"GDPC" + bytes(range(256)) * 16 + b"game payload\n")
    with open(os.path.join(build, "launcher", "hpmmo_launcher.exe"), "wb") as handle:
        handle.write(b"MZ" + b"\x00" * 256 + b"fake native launcher\n")
    with open(os.path.join(build, "launcher", "assets", "hpmmo_banner.jpg"), "wb") as handle:
        handle.write(b"\xff\xd8\xff\xe0fake jpeg\n")
    return build


def package(build: str, out: str) -> subprocess.CompletedProcess:
    return python_tool(PACKAGER, "--build-dir", build, "--client-version", CLIENT_VERSION,
                       "--content-version", CONTENT_VERSION, "--platform", PLATFORM, "--out", out)


def build_manifest(out: str, key: str, **overrides) -> subprocess.CompletedProcess:
    fields = {
        "--channel": "dev",
        "--client-version": CLIENT_VERSION,
        "--min-launcher-version": CLIENT_VERSION,
        "--protocol-version": "4",
        "--protocol-min": "4",
        "--protocol-max": "4",
        "--content-version": CONTENT_VERSION,
        "--server-version": "0.7.0",
        "--schema-version": "4",
        "--platform": PLATFORM,
        "--base-url": BASE_URL,
        "--published-at": PUBLISHED_AT,
        "--release-notes": "rehearsal manifest",
    }
    fields.update({k: str(v) for k, v in overrides.items()})
    args = ["--artifact", os.path.join(out, rc.artifact_name(CLIENT_VERSION, PLATFORM))]
    for name, value in fields.items():
        args += [name, value]
    return python_tool(MANIFEST_TOOL, *args, "--key", key, "--out", out)


def load_manifest(path: str) -> dict:
    with open(path, encoding="utf-8") as handle:
        return json.load(handle)


def free_port() -> int:
    with socket.socket() as sock:
        sock.bind(("127.0.0.1", 0))
        return sock.getsockname()[1]


def wait_for_https(port: int, context: ssl.SSLContext, timeout: float = 25.0) -> dict:
    deadline = time.time() + timeout
    last = None
    while time.time() < deadline:
        try:
            connection = http.client.HTTPSConnection("127.0.0.1", port, context=context, timeout=3)
            connection.request("GET", "/health")
            response = connection.getresponse()
            body = response.read()
            connection.close()
            if response.status == 200:
                return json.loads(body)
        except Exception as exc:  # noqa: BLE001 - the service may not be up yet
            last = exc
            time.sleep(0.2)
    raise RuntimeError("the status service never answered over HTTPS: %r" % (last,))


def https_get(port: int, path: str, context: ssl.SSLContext, method: str = "GET"):
    connection = http.client.HTTPSConnection("127.0.0.1", port, context=context, timeout=10)
    connection.request(method, path)
    response = connection.getresponse()
    body = response.read()
    return response.status, dict(response.getheaders()), body, connection


def fixture() -> dict:
    """Builds the shared rehearsal fixture exactly once: a key pair, a packaged
    artifact and a signed manifest, all under the temp root."""
    global _FIXTURE
    if _FIXTURE:
        return _FIXTURE
    root = temp_dir("fixture-")
    key, pub = make_keypair(root)
    build = make_build_tree(root)
    out = os.path.join(root, "dist")
    os.makedirs(out)

    result = package(build, out)
    check(result.returncode == 0, "[fixture] the packager builds an artifact from a clean build tree")
    if result.returncode != 0:
        note(result.stdout + result.stderr)
        return {}

    result = build_manifest(out, key)
    check(result.returncode == 0, "[fixture] the manifest is generated, signed and self-verified")
    if result.returncode != 0:
        note(result.stdout + result.stderr)
        return {}
    check("MANIFEST OK" in result.stdout, "[fixture] the tool proves its own output before anyone can publish it")

    _FIXTURE = {
        "root": root,
        "key": key,
        "pub": pub,
        "build": build,
        "out": out,
        "artifact": os.path.join(out, rc.artifact_name(CLIENT_VERSION, PLATFORM)),
        "manifest": os.path.join(out, "manifest.json"),
    }
    return _FIXTURE


# --- cases -------------------------------------------------------------------

def case_package(keep: bool) -> None:
    case = fixture()
    if not case:
        check(False, "[package] the fixture could not be built")
        return
    artifact, build = case["artifact"], case["build"]

    result = python_tool(PACKAGER, "--build-dir", build, "--client-version", CLIENT_VERSION,
                         "--content-version", CONTENT_VERSION, "--check")
    check(result.returncode == 0, "[package] a clean build tree passes --check")
    note(result.stdout + result.stderr)
    check(os.path.isfile(artifact) and os.path.getsize(artifact) > 0, "[package] the artifact exists")
    check(os.path.basename(artifact) == rc.artifact_name(CLIENT_VERSION, PLATFORM),
          "[package] the artifact follows the version-directory naming convention")

    # determinism: same tree, second output directory, identical bytes
    second = temp_dir("package-again-")
    package(build, second)
    check(rc.sha256_file(artifact) == rc.sha256_file(os.path.join(second, os.path.basename(artifact))),
          "[package] the same build tree produces identical artifact bytes")

    with zipfile.ZipFile(artifact) as archive:
        names = archive.namelist()
        check("release.json" in names, "[package] the package carries release.json")
        check("hpmmo.pck" in names, "[package] the game payload is flat at the archive root")
        check(any(name.lower() == "hpmmo.exe" for name in names),
              "[package] the game executable is at the archive root (the launcher resolves <versionDir>/HPMMO.exe)")
        check(all(not name.startswith("hpmmo-client-") for name in names),
              "[package] the artifact has no wrapper directory to hide the executable from the launcher")
        check("launcher/hpmmo_launcher.exe" in names,
              "[package] the launcher payload keeps its own directory")
        release_doc = json.loads(archive.read("release.json").decode("utf-8"))
        check(release_doc.get("client_version") == CLIENT_VERSION
              and release_doc.get("content_version") == CONTENT_VERSION
              and release_doc.get("platform") == PLATFORM,
              "[package] release.json records the versions the manifest will claim")
        listed = sorted(entry["path"] for entry in release_doc["files"])
        present = sorted(name for name in names if name != "release.json")
        check(listed == present, "[package] release.json lists exactly the packaged files")
        check(all(rc.sha256_bytes(archive.read(entry["path"])) == entry["sha256"]
                  for entry in release_doc["files"]),
              "[package] every recorded hash matches the bytes in the artifact")
        check({entry["role"] for entry in release_doc["files"]} == {"game", "launcher"},
              "[package] release.json marks which files are game content")

        offenders = []
        for name in names:
            reason = rc.path_refusal(name)
            if reason:
                offenders.append("%s (%s)" % (name, reason))
        check(not offenders, "[package] the artifact contains no user data, cache or secret path (%s)"
              % (offenders or "none"))

    # a poisoned tree must be refused: user data, key material, token content
    poisoned = temp_dir("poisoned-userdata-")
    poisoned_build = make_build_tree(poisoned)
    os.makedirs(os.path.join(poisoned_build, "client", "screenshots"))
    with open(os.path.join(poisoned_build, "client", "screenshots", "shot1.png"), "wb") as handle:
        handle.write(b"\x89PNG fake screenshot")
    os.makedirs(os.path.join(poisoned_build, "client", "settings"))
    with open(os.path.join(poisoned_build, "client", "settings", "keybinds.cfg"), "w", encoding="utf-8") as handle:
        handle.write("jump=space\n")
    result = package(poisoned_build, os.path.join(poisoned, "dist"))
    combined = result.stdout + result.stderr
    check(result.returncode != 0, "[package] a tree containing user data is refused")
    check("screenshots" in combined or "keybinds" in combined,
          "[package] the refusal names the offending path")

    poisoned2 = temp_dir("poisoned-key-")
    poisoned2_build = make_build_tree(poisoned2)
    with open(os.path.join(poisoned2_build, "launcher", "release.key.pem"), "w", encoding="utf-8") as handle:
        handle.write("-----BEGIN PRIVATE KEY-----\nnot a real key\n-----END PRIVATE KEY-----\n")
    result = package(poisoned2_build, os.path.join(poisoned2, "dist"))
    check(result.returncode != 0, "[package] a tree carrying key material is refused")

    poisoned3 = temp_dir("poisoned-token-")
    poisoned3_build = make_build_tree(poisoned3)
    with open(os.path.join(poisoned3_build, "client", "notes.txt"), "w", encoding="utf-8") as handle:
        handle.write("build notes\nHPMMO_SERVICE_TOKEN=abcdef123456\n")
    result = package(poisoned3_build, os.path.join(poisoned3, "dist"))
    check(result.returncode != 0, "[package] a file containing a service token is refused")

    poisoned4 = temp_dir("poisoned-layout-")
    poisoned4_build = make_build_tree(poisoned4)
    os.makedirs(os.path.join(poisoned4_build, "extras"))
    with open(os.path.join(poisoned4_build, "extras", "readme.txt"), "w", encoding="utf-8") as handle:
        handle.write("unexpected top-level directory\n")
    result = package(poisoned4_build, os.path.join(poisoned4, "dist"))
    check(result.returncode != 0, "[package] an unexpected top-level directory is refused")

    # The signer is the last gate: a hand-made (or edited) artifact carrying
    # user data must not get a signature that would bless it.
    handmade = temp_dir("handmade-")
    handmade_zip = os.path.join(handmade, rc.artifact_name(CLIENT_VERSION, PLATFORM))
    with zipfile.ZipFile(handmade_zip, "w") as archive:
        archive.writestr("hpmmo.pck", b"payload")
        archive.writestr("screenshots/shot1.png", b"\x89PNG")
        archive.writestr("release.json", "{}")
    result = build_manifest(handmade, case["key"])
    check(result.returncode != 0, "[package] the signer refuses to sign a package containing user data")
    check("refusing to sign" in (result.stdout + result.stderr),
          "[package] the signer's refusal says what it saw")


def case_manifest(keep: bool) -> None:
    case = fixture()
    if not case:
        check(False, "[manifest] the fixture could not be built")
        return
    out, key, pub, manifest_path = case["out"], case["key"], case["pub"], case["manifest"]

    manifest = load_manifest(manifest_path)
    expected_fields = ["channel", "client_version", "min_launcher_version", "protocol_version",
                       "protocol_min", "protocol_max", "content_version", "content_sha256",
                       "server_version", "schema_version", "platform", "published_at",
                       "release_notes", "artifacts"]
    check(list(manifest.keys()) == expected_fields,
          "[manifest] the document carries exactly the contracted fields, in order")
    check(manifest["published_at"] == PUBLISHED_AT, "[manifest] --published-at pins the timestamp")
    check(manifest["channel"] == "dev" and manifest["platform"] == PLATFORM,
          "[manifest] the channel and platform are recorded")
    check(re.match(r"^[0-9a-f]{64}$", manifest["content_sha256"]) is not None,
          "[manifest] the content hash is a sha256")
    entry = manifest["artifacts"][0]
    check(entry["kind"] == "full" and entry["from_version"] is None,
          "[manifest] a full artifact records from_version as null")
    check(entry["url"] == BASE_URL + "/" + rc.artifact_name(CLIENT_VERSION, PLATFORM),
          "[manifest] the artifact URL is the documented <base>/<file> shape")
    check(entry["size"] == os.path.getsize(case["artifact"]),
          "[manifest] the artifact size is recorded from the file")
    check(entry["sha256"] == rc.sha256_file(case["artifact"]),
          "[manifest] the artifact sha256 is recorded from the file")

    with open(manifest_path + ".sig", encoding="ascii") as handle:
        signature_line = handle.read()
    check(signature_line.count("\n") == 1 and signature_line.endswith("\n"),
          "[manifest] the signature file is exactly one line")
    try:
        signature = rc.b64_decode(signature_line)
        decoded = True
    except Exception as exc:  # noqa: BLE001
        decoded = False
        signature = b""
        note(str(exc))
    check(decoded and len(signature) == 64,
          "[manifest] the signature decodes to a raw 64-byte Ed25519 signature")
    with open(manifest_path + ".keyid", encoding="utf-8") as handle:
        keyid = json.load(handle)
    check(keyid.get("key_id") == spki_pin(pub), "[manifest] the key id is the pinned key's SPKI sha256")
    check(keyid.get("algorithm") == "ed25519" and keyid.get("sig_file") == "manifest.json.sig",
          "[manifest] the key id sidecar names the algorithm and the signature file")

    # determinism: identical inputs, a pinned timestamp, identical bytes/signature
    other = temp_dir("manifest-again-")
    shutil.copy(case["artifact"], other)
    result = build_manifest(other, key)
    check(result.returncode == 0, "[manifest] the manifest can be regenerated from the same artifact")
    if result.returncode == 0:
        check(open(manifest_path, "rb").read() == open(os.path.join(other, "manifest.json"), "rb").read(),
              "[manifest] identical inputs produce identical manifest bytes")
        check(open(manifest_path + ".sig", "rb").read() == open(os.path.join(other, "manifest.json.sig"), "rb").read(),
              "[manifest] identical inputs produce an identical signature")

    result = python_tool(MANIFEST_TOOL, "--verify", "--manifest", manifest_path,
                         "--pubkey", pub, "--artifacts", out)
    check(result.returncode == 0, "[manifest] --verify accepts the manifest and its artifact")
    note(result.stdout + result.stderr)

    sums = os.path.join(out, "SHA256SUMS")
    check(os.path.isfile(sums), "[manifest] SHA256SUMS is written next to the manifest")
    if os.path.isfile(sums):
        lines = [line.split("  ", 1) for line in open(sums, encoding="ascii").read().strip().split("\n")]
        check({name for _digest, name in lines} == {"manifest.json", "manifest.json.sig", "manifest.json.keyid"},
              "[manifest] SHA256SUMS covers the manifest set")
        check(all(rc.sha256_file(os.path.join(out, name)) == digest for digest, name in lines),
              "[manifest] every SHA256SUMS digest matches the file it names")


def case_tamper(keep: bool) -> None:
    case = fixture()
    if not case:
        check(False, "[tamper] the fixture could not be built")
        return
    out, pub, manifest_path = case["out"], case["pub"], case["manifest"]

    def copied(names=("manifest.json", "manifest.json.sig", "manifest.json.keyid")) -> str:
        work = temp_dir("tamper-")
        for name in names:
            shutil.copy(os.path.join(out, name), work)
        return work

    # 1. one appended byte in the manifest
    work = copied()
    with open(os.path.join(work, "manifest.json"), "ab") as handle:
        handle.write(b" ")
    result = python_tool(MANIFEST_TOOL, "--verify", "--manifest", os.path.join(work, "manifest.json"),
                         "--pubkey", pub, "--no-artifacts")
    check(result.returncode != 0, "[tamper] a manifest with one appended byte fails verification")
    check("signature does NOT verify" in (result.stdout + result.stderr),
          "[tamper] the failure names the signature, not something incidental")

    # 2. a single edited field inside the signed bytes
    work2 = copied()
    raw = open(os.path.join(work2, "manifest.json"), "rb").read()
    with open(os.path.join(work2, "manifest.json"), "wb") as handle:
        handle.write(raw.replace(b'"0.7.0"', b'"0.7.1"', 1))
    result = python_tool(MANIFEST_TOOL, "--verify", "--manifest", os.path.join(work2, "manifest.json"),
                         "--pubkey", pub, "--no-artifacts")
    check(result.returncode != 0, "[tamper] an edited version field fails verification")

    # 3. a tampered artifact
    work3 = copied()
    shutil.copy(case["artifact"], work3)
    local = os.path.join(work3, os.path.basename(case["artifact"]))
    payload = bytearray(open(local, "rb").read())
    payload[-1] ^= 0xFF
    with open(local, "wb") as handle:
        handle.write(bytes(payload))
    result = python_tool(MANIFEST_TOOL, "--verify", "--manifest", os.path.join(work3, "manifest.json"),
                         "--pubkey", pub, "--artifacts", work3)
    check(result.returncode != 0, "[tamper] an artifact whose bytes changed fails verification")
    check("hashes to" in (result.stdout + result.stderr), "[tamper] the failure reports the hash mismatch")

    # 4. the right manifest under the wrong key / an unexpected key id
    _other_key, other_pub = make_keypair(case["root"], "other")
    result = python_tool(MANIFEST_TOOL, "--verify", "--manifest", manifest_path,
                         "--pubkey", other_pub, "--no-artifacts")
    check(result.returncode != 0, "[tamper] a manifest signed by another key is refused")
    result = python_tool(MANIFEST_TOOL, "--verify", "--manifest", manifest_path,
                         "--pubkey", pub, "--key-id", spki_pin(other_pub), "--no-artifacts")
    check(result.returncode != 0, "[tamper] an unexpected key id is refused even when the signature is good")

    # 5. a manifest missing its signature is not a release
    work4 = copied(("manifest.json",))
    result = python_tool(MANIFEST_TOOL, "--verify", "--manifest", os.path.join(work4, "manifest.json"),
                         "--pubkey", pub, "--no-artifacts")
    check(result.returncode != 0, "[tamper] an unsigned manifest is refused")


def gate(manifest_path: str, client: str, launcher: str, protocol: str | None = "4",
         content: str | None = CONTENT_VERSION) -> dict:
    args = ["--gate", "--manifest", manifest_path, "--installed-client", client,
            "--installed-launcher", launcher]
    if protocol is not None:
        args += ["--installed-protocol", protocol]
    if content is not None:
        args += ["--installed-content", content]
    result = python_tool(MANIFEST_TOOL, *args)
    if result.returncode != 0:
        note(result.stdout + result.stderr)
        return {}
    return json.loads(result.stdout)


def case_gate(keep: bool) -> None:
    case = fixture()
    if not case:
        check(False, "[gate] the fixture could not be built")
        return
    key, out, base = case["key"], case["out"], case["manifest"]

    verdict = gate(base, CLIENT_VERSION, CLIENT_VERSION)
    check(verdict.get("client_update") == "none" and verdict.get("playable_online") is True,
          "[gate] an up-to-date client needs no download and can play")
    check(verdict.get("protocol_compatible") is True, "[gate] the documented protocol range is satisfied")

    # --- a server-only bump: same client artifact, new server/schema version ---
    server_only = temp_dir("server-only-")
    shutil.copy(case["artifact"], server_only)
    result = build_manifest(server_only, key, **{"--server-version": "0.7.1", "--schema-version": "5"})
    check(result.returncode == 0, "[gate] a server-only bump can be published against the same artifact")
    if result.returncode == 0:
        bumped_path = os.path.join(server_only, "manifest.json")
        bumped = load_manifest(bumped_path)
        original = load_manifest(base)
        check(bumped["server_version"] == "0.7.1" and bumped["schema_version"] == 5,
              "[gate] the republished manifest records the new server and schema versions")
        check(bumped["client_version"] == original["client_version"]
              and bumped["content_version"] == original["content_version"]
              and bumped["content_sha256"] == original["content_sha256"]
              and bumped["artifacts"][0]["sha256"] == original["artifacts"][0]["sha256"],
              "[gate] the server-only bump leaves client version, content and artifact untouched")
        check(open(bumped_path, "rb").read() != open(base, "rb").read(),
              "[gate] the republished manifest is a new, separately signed document")
        verdict = gate(bumped_path, CLIENT_VERSION, CLIENT_VERSION)
        check(verdict.get("client_update") == "none",
              "[gate] a server-only bump does NOT force a client download")
        check(verdict.get("playable_online") is True,
              "[gate] the client stays playable online across a server-only patch")

    # --- a real client bump ---
    client_bump = temp_dir("client-bump-")
    shutil.copy(case["artifact"], client_bump)
    result = build_manifest(client_bump, key, **{"--client-version": "0.8.0"})
    if result.returncode == 0:
        verdict = gate(os.path.join(client_bump, "manifest.json"), CLIENT_VERSION, CLIENT_VERSION)
        check(verdict.get("client_update") == "required",
              "[gate] an older installed client requires a download")
        check(verdict.get("playable_online") is False,
              "[gate] a required update blocks going online until it is applied")

    # --- the protocol floor moves ---
    protocol_bump = temp_dir("protocol-bump-")
    shutil.copy(case["artifact"], protocol_bump)
    result = build_manifest(protocol_bump, key, **{"--protocol-version": "5", "--protocol-min": "5"})
    if result.returncode == 0:
        verdict = gate(os.path.join(protocol_bump, "manifest.json"), CLIENT_VERSION,
                       CLIENT_VERSION, protocol="4")
        check(verdict.get("protocol_compatible") is False,
              "[gate] a client outside the accepted protocol range is not allowed online")
        check(verdict.get("playable_online") is False, "[gate] an incompatible protocol blocks play")

    # --- the launcher minimum moves ---
    launcher_bump = temp_dir("launcher-bump-")
    shutil.copy(case["artifact"], launcher_bump)
    result = build_manifest(launcher_bump, key, **{"--min-launcher-version": "0.9.0"})
    if result.returncode == 0:
        verdict = gate(os.path.join(launcher_bump, "manifest.json"), CLIENT_VERSION, CLIENT_VERSION)
        check(verdict.get("launcher_update") == "required",
              "[gate] a launcher below the minimum must self-update first")
        check(verdict.get("playable_online") is False, "[gate] a launcher that must update blocks play")

    # --- content mismatch with an otherwise current client: repair, not download ---
    verdict = gate(base, CLIENT_VERSION, CLIENT_VERSION, content="2026.01.01-1")
    check(verdict.get("content_status") == "repair_required",
          "[gate] a current client with the wrong content is a repair, not an update")
    check(verdict.get("client_update") == "none",
          "[gate] repair does not claim a download is needed")

    # --- a newer installed client on an older channel is not forced backwards ---
    verdict = gate(base, "0.9.0", CLIENT_VERSION)
    check(verdict.get("client_update") == "none",
          "[gate] an installed client ahead of the channel is not silently downgraded")


def case_tls_endpoint(keep: bool) -> None:
    case = fixture()
    if not case:
        check(False, "[tls] the fixture could not be built")
        return
    root = case["root"]
    publish_root = os.path.join(root, "release-root")
    channel_dir = os.path.join(publish_root, "channels", "dev")
    os.makedirs(channel_dir, exist_ok=True)
    artifact_name = rc.artifact_name(CLIENT_VERSION, PLATFORM)
    shutil.copy(case["artifact"], publish_root)
    shutil.copy(case["artifact"] + ".sha256", publish_root)
    for name in ("manifest.json", "manifest.json.sig", "manifest.json.keyid", "SHA256SUMS"):
        shutil.copy(os.path.join(case["out"], name), channel_dir)

    tls_dir = os.path.join(root, "tls")
    if not BASH:
        print("SKIP: no usable bash found (set HPMMO_BASH); the certificate and the HTTPS endpoint "
              "cannot be rehearsed on this machine.")
        return
    result = subprocess.run([BASH, MAKE_CERT, "--host", "127.0.0.1", "--san", "DNS:localhost",
                             "--out", tls_dir, "--force"], capture_output=True, text=True, timeout=300)
    check(result.returncode == 0, "[tls] make_cert.sh generates the release certificate")
    if result.returncode != 0:
        note(result.stdout + result.stderr)
        return
    cert = os.path.join(tls_dir, "release-cert.pem")
    key = os.path.join(tls_dir, "release-key.pem")
    match = re.search(r"PIN THIS IN THE LAUNCHER \(SPKI sha256\):\s*\n\s*([0-9a-f]{64})", result.stdout)
    check(bool(match), "[tls] make_cert.sh prints the SPKI sha256 the launcher pins")
    if not match:
        return
    pin = match.group(1)
    check(pin == spki_pin_of_certificate(cert), "[tls] the printed pin equals the certificate's SPKI sha256")
    if os.name == "posix":
        check(os.stat(key).st_mode & 0o077 == 0,
              "[tls] the private key is written with no group/other access")
    else:
        note("windows: POSIX key file modes are not applicable to this rehearsal")

    enddate = openssl("x509", "-in", cert, "-noout", "-enddate").stdout.decode().strip()
    check(enddate.startswith("notAfter="), "[tls] the certificate carries an expiry")
    try:
        expires = dt.datetime.strptime(enddate.split("=", 1)[1].strip(), "%b %d %H:%M:%S %Y %Z")
        days = (expires - dt.datetime.utcnow()).days
        check(abs(days - CERT_DAYS) <= 1, "[tls] the validity is ~%d days (got %d)" % (CERT_DAYS, days))
    except ValueError as exc:
        check(False, "[tls] the expiry could not be parsed: %s" % exc)
    text = openssl("x509", "-in", cert, "-noout", "-text").stdout.decode()
    check("IP Address:127.0.0.1" in text, "[tls] the SAN names the host the launcher connects to")
    check("DNS:localhost" in text, "[tls] extra SANs are honoured")

    # a public bind without TLS must be refused (the box must not expose cleartext)
    refused = subprocess.run([sys.executable, STATUS_SERVICE, "--port", str(free_port())],
                             env={**os.environ, "HPMMO_STATUS_HOST": "0.0.0.0",
                                  "HPMMO_STATUS_ALLOW_NONLOOPBACK": "1"},
                             capture_output=True, text=True, timeout=90)
    check(refused.returncode == 2 and "TLS" in refused.stderr,
          "[tls] a non-loopback bind without TLS is refused (exit %s)" % refused.returncode)

    state_dir = os.path.join(root, "state")
    os.makedirs(state_dir, exist_ok=True)
    with open(os.path.join(state_dir, "status.json"), "w", encoding="utf-8") as handle:
        handle.write(json.dumps({"state": "ONLINE", "release": "rel-base", "previous_release": "",
                                 "since": "2026-10-04T00:00:00Z", "message": "rehearsal"}) + "\n")
    port = free_port()
    env = {**os.environ,
           "HPMMO_STATE_DIR": state_dir,
           "HPMMO_STATUS_RELEASES_ROOT": publish_root,
           "HPMMO_STATUS_TLS_CERT": cert,
           "HPMMO_STATUS_TLS_KEY": key}
    proc = subprocess.Popen([sys.executable, STATUS_SERVICE, "--port", str(port)],
                            env=env, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
    # Full verification, not a bypass: the certificate is self-signed, so it is
    # loaded as the trust anchor exactly as a pinned client would pin it.
    context = ssl.create_default_context(cafile=cert)
    try:
        health = wait_for_https(port, context)
        check(health.get("tls") is True, "[tls] the service reports that it is serving TLS")

        code, _headers, body, connection = https_get(port, "/status", context)
        connection.close()
        check(code == 200 and json.loads(body).get("state") == "ONLINE",
              "[tls] /status is served over the pinned certificate")

        # The wire-level pin check: complete a TLS handshake and hash the peer's
        # SubjectPublicKeyInfo, which is exactly what the launcher does.
        with socket.create_connection(("127.0.0.1", port), timeout=10) as raw:
            with context.wrap_socket(raw, server_hostname="127.0.0.1") as tls:
                peer_der = tls.getpeercert(binary_form=True)
        der_path = os.path.join(root, "peer.der")
        with open(der_path, "wb") as handle:
            handle.write(peer_der)
        public_key = openssl("x509", "-inform", "DER", "-in", der_path, "-noout", "-pubkey").stdout
        der = openssl("pkey", "-pubin", "-outform", "DER", stdin=public_key).stdout
        check(hashlib.sha256(der).hexdigest() == pin,
              "[tls] the certificate actually on the wire hashes to the pin the launcher embeds")

        code, _headers, body, connection = https_get(port, "/tls/spki", context)
        connection.close()
        check(code == 200 and json.loads(body)["spki_sha256"] == pin,
              "[tls] the service reports the same pin it serves")

        # the manifest, over TLS, verified exactly as the launcher verifies it:
        # the served bytes and the served signature, against the pinned key
        served_path = os.path.join(root, "served-manifest.json")
        for remote, local in (("manifest.json", served_path),
                              ("manifest.json.sig", served_path + ".sig"),
                              ("manifest.json.keyid", served_path + ".keyid")):
            status, _headers, payload, connection = https_get(
                port, "/releases/channels/dev/" + remote, context)
            connection.close()
            check(status == 200, "[tls] the served %s answers 200" % remote)
            with open(local, "wb") as handle:
                handle.write(payload)
        manifest_bytes = open(served_path, "rb").read()
        check(json.loads(manifest_bytes)["client_version"] == CLIENT_VERSION,
              "[tls] the served manifest is the manifest that was published")
        result = python_tool(MANIFEST_TOOL, "--verify", "--manifest", served_path,
                             "--pubkey", case["pub"], "--artifacts", publish_root)
        check(result.returncode == 0,
              "[tls] the manifest fetched over HTTPS verifies against the pinned key")
        note(result.stdout + result.stderr)

        code, headers, body, connection = https_get(port, "/releases/" + artifact_name, context,
                                                    method="HEAD")
        connection.close()
        check(code == 200 and int(headers.get("Content-Length", "0"))
              == os.path.getsize(case["artifact"]),
              "[tls] HEAD reports the artifact size for resume and disk-space checks")

        status, _headers, body, connection = https_get(port, "/releases/" + artifact_name, context)
        connection.close()
        check(status == 200 and hashlib.sha256(body).hexdigest() == rc.sha256_file(case["artifact"]),
              "[tls] the artifact downloads byte-for-byte over HTTPS")

        for path in ("/releases/../release-key.pem", "/releases/channels/dev/.hidden",
                     "/releases/channels/dev/nope.json", "/releases/"):
            status, _headers, _body, connection = https_get(port, path, context)
            connection.close()
            check(status == 404, "[tls] %s is refused with 404" % path)
    finally:
        proc.terminate()
        try:
            proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            proc.kill()
        stderr = proc.communicate()[1] or ""
        if "Traceback" in stderr:
            note("status service stderr:\n" + stderr)
        if stderr and VERBOSE:
            note(stderr)


def case_contract(keep: bool) -> None:
    check(os.path.isfile(CONTRACT_DOC), "[contract] server/docs/release-contract.md exists")
    check(os.path.isfile(WORKFLOW), "[contract] client/.github/workflows/client-release.yml exists")
    check(os.path.isfile(os.path.join(TOOLS, "keys", "README.md")),
          "[contract] the key custody notes exist at client/tools/release/keys/README.md")
    check(os.path.isfile(os.path.join(TOOLS, "keys", ".gitignore")),
          "[contract] key material is gitignored inside the keys directory")
    for tool in ("package_client.py", "gen_manifest.py", "release_common.py",
                 "windows-desktop.export_presets.cfg"):
        check(os.path.isfile(os.path.join(TOOLS, tool)), "[contract] %s is present" % tool)

    if os.path.isfile(WORKFLOW):
        workflow = open(WORKFLOW, encoding="utf-8").read()
        check("branches: [release]" in workflow, "[contract] only the release branch triggers a build")
        check("concurrency:" in workflow, "[contract] the workflow uses concurrency groups")
        check("group: client-publish-" in workflow, "[contract] publishing is serialised per channel")
        check("cancel-in-progress: false" in workflow, "[contract] a publish is never cancelled mid-flight")
        check("environment:" in workflow and "client-release" in workflow,
              "[contract] flipping a channel sits behind the client-release environment gate")
        check("inputs.publish" in workflow, "[contract] publishing needs an explicit manual input")
        check("HPMMO_CLIENT_SIGNING_KEY" in workflow and "exit 1" in workflow,
              "[contract] the workflow fails closed when the signing key is absent")
        check("--verify" in workflow, "[contract] the workflow verifies what it just signed")
        check("actions/download-artifact@v4" in workflow,
              "[contract] the publish job consumes the built artifact instead of rebuilding")
        check("GODOT_VERSION: '4.7.2'" in workflow, "[contract] the engine version is pinned")
        check("if: github.event_name == 'workflow_dispatch'" in workflow,
              "[contract] a push can never reach the publish job")

    doc = open(CONTRACT_DOC, encoding="utf-8").read() if os.path.isfile(CONTRACT_DOC) else ""
    for field in ("client_version", "min_launcher_version", "protocol_version", "content_version",
                  "server_version", "schema_version"):
        check(field in doc, "[contract] the document states which field gates what (%s)" % field)
    check("server-only" in doc, "[contract] the document states that a server-only patch needs no client download")
    check("SPKI" in doc and "825" in doc, "[contract] the document records the certificate pin and validity")
    check("don't" not in doc or True, "[contract] (no-op)")

    # no key material anywhere beside the release tooling
    offenders: list[str] = []
    for base in (TOOLS, os.path.join(CLIENT, ".github")):
        for dirpath, dirnames, filenames in os.walk(base):
            dirnames[:] = [name for name in dirnames if name not in (".git", "__pycache__")]
            for name in filenames:
                path = os.path.join(dirpath, name)
                rel = os.path.relpath(path, base).replace("\\", "/")
                if rc.path_refusal(rel):
                    continue
                if looks_like_secret(path):
                    offenders.append(os.path.relpath(path, CLIENT))
    check(not offenders,
          "[contract] no key material or token is committed with the release tooling (%s)" % (offenders or "clean"))

    # the refusal rules themselves, exercised directly
    check(rc.path_refusal("client/screenshots/a.png"), "[contract] screenshots are user data")
    check(rc.path_refusal("settings/keybinds.cfg"), "[contract] a keybinds directory is user data")
    check(rc.path_refusal("logs/launcher.log"), "[contract] logs are user data")
    check(rc.path_refusal(".godot/editor/x.cfg"), "[contract] the editor cache is refused")
    check(rc.path_refusal("launcher/release.key.pem"), "[contract] .pem files are refused")
    check(rc.path_refusal("deploy/hpmmo.env"), "[contract] environment files are refused")
    check(not rc.path_refusal("client/hpmmo.pck"), "[contract] ordinary payload paths are allowed")
    check(not rc.path_refusal("launcher/assets/hpmmo_banner.jpg"), "[contract] ordinary assets are allowed")


CASES = {
    "contract": case_contract,
    "package": case_package,
    "manifest": case_manifest,
    "tamper": case_tamper,
    "gate": case_gate,
    "tls": case_tls_endpoint,
}
ORDER = ["contract", "package", "manifest", "tamper", "gate", "tls"]


def main() -> int:
    global VERBOSE, KEEP, _TEMP_ROOT
    parser = argparse.ArgumentParser(description="HPMMO client release pipeline rehearsal")
    parser.add_argument("--case", action="append", default=[], help="run only these cases")
    parser.add_argument("--keep", action="store_true", help="keep the temp rehearsal dirs")
    parser.add_argument("--verbose", action="store_true", help="show tool output")
    args = parser.parse_args()
    VERBOSE = args.verbose
    KEEP = args.keep

    if rc is None:
        print("ERROR: cannot import the release tools from %s (set HPMMO_CLIENT_REPO)" % TOOLS)
        return 2
    missing = [path for path in (PACKAGER, MANIFEST_TOOL, STATUS_SERVICE, MAKE_CERT)
               if not os.path.isfile(path)]
    if missing:
        print("ERROR: missing tooling: %s" % ", ".join(missing))
        return 2
    global BASH
    BASH = find_bash()
    if openssl("version").returncode != 0:
        print("SKIP: openssl is not available (set HPMMO_OPENSSL); the signing tools need it.")
        return 2

    selected = args.case or ORDER
    unknown = [name for name in selected if name not in CASES]
    if unknown:
        print("ERROR: unknown case(s): %s (known: %s)" % (", ".join(unknown), ", ".join(ORDER)))
        return 2

    _TEMP_ROOT = tempfile.mkdtemp(prefix="hpmmo-release-")
    print("HPMMO release pipeline rehearsal")
    print("client repo: %s" % CLIENT)
    print("temp root:   %s" % _TEMP_ROOT)
    for name in selected:
        say("case: %s" % name)
        started = time.time()
        try:
            CASES[name](args.keep)
        except Exception as exc:  # noqa: BLE001 - a harness crash is a failed check
            import traceback
            failures.append("[%s] harness error: %s" % (name, exc))
            print("FAIL: [%s] harness error: %s" % (name, exc))
            if VERBOSE:
                traceback.print_exc()
        print("    (%s took %.1fs)" % (name, time.time() - started))

    if not args.keep and _TEMP_ROOT:
        shutil.rmtree(_TEMP_ROOT, ignore_errors=True)

    print("\nRELEASE RESULT: %d checks, %d failures" % (checks, len(failures)))
    for failure in failures:
        print("  - " + failure)
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
