extends RefCounted
class_name HPProtocol

## Authoritative protocol shared by the world server and every client.
## OWNER: server repository. The client copy is generated by `dev.ps1 sync-sim`;
## never edit `client/addons/hpmmo_sim/` by hand.
##
## This file is the source of the contract document `contracts/protocol.md`
## (generated by `client/tools/workspace/extract_protocol.py`).

## Bumped whenever a message shape, semantics, or rule constant changes in a way
## that makes older clients disagree. Clients whose version differs are refused
## at join instead of silently desyncing.
## v5: per-map state and the server-authorized map-transfer exchange.
## v6: encounter lifecycle - mob AI state in the snapshot state byte and the
##     boss telegraph message (server-owned release tick, client-rendered
##     warning) from plan.md Phase 11.
const PROTOCOL_VERSION := 6

## Simulation / replication rates.
const SIM_HZ := 20
const SIM_DT := 1.0 / 20.0
const SNAPSHOT_HZ := 10
const SNAPSHOT_INTERVAL_TICKS := SIM_HZ / SNAPSHOT_HZ

## How long a client's movement input stays valid while packets are missing.
## Input older than this is discarded (the player simply stops accelerating).
const INPUT_BUFFER_MS := 120
## A cast request arriving this close to the end of recovery is queued instead
## of refused (plan Phase 5: bounded input buffer, 100-150 ms).
const CAST_QUEUE_MS := 120
## Damage within this window of a kill credits the player with the reward.
const KILL_CREDIT_MS := 10000

## ENet channels. Keeping movement off the reliable channel is what stops a lost
## packet from stalling the player in place.
const CH_SNAPSHOT := 0
const CH_EVENT := 1
const CH_INTENT := 2
const CH_INPUT := 3

## Interest filtering.
const INTEREST_RADIUS := 70.0
const MAX_ENTITIES_PER_SNAPSHOT := 30
const DEFAULT_MAP := "grounds"

## Map transfer (plan.md Phase 8). A client that requested a transfer but never
## acknowledged readiness must not strand its character between maps, so the
## reservation expires and the character returns to its last valid safe spawn.
## Test affordance: HPMMO_DEV_TRANSFER_TIMEOUT_MS (never set in production).
const TRANSFER_TIMEOUT_MS := 15000

static func transfer_timeout_ms() -> int:
	var raw := OS.get_environment("HPMMO_DEV_TRANSFER_TIMEOUT_MS")
	if raw != "" and raw.is_valid_int():
		return maxi(250, int(raw))
	return TRANSFER_TIMEOUT_MS

## Rejection reasons a client must be able to render without a new server build.
const REJECT_OK := ""
const REJECT_UNKNOWN_SPELL := "unknown_spell"
const REJECT_DEAD := "dead"
const REJECT_MOUNTED := "mounted"
const REJECT_COOLDOWN := "cooldown"
const REJECT_NO_MANA := "no_mana"
const REJECT_RANGE := "out_of_range"
const REJECT_NO_TARGET := "no_target"
const REJECT_PROTECTED := "protected"
const REJECT_LINE_OF_SIGHT := "no_line_of_sight"
const REJECT_INPUT_BUFFER := "input_buffer"
const REJECT_ZONE := "wrong_zone"
const REJECT_STATE := "invalid_state"
## Map transfer (plan.md Phase 8).
const REJECT_TRANSFER_PENDING := "transfer_pending"
const REJECT_NO_PORTAL := "no_portal"
const REJECT_WRONG_MAP := "wrong_map"
const REJECT_NO_FLIGHT := "no_flight"
const REJECT_MAP_UNAVAILABLE := "map_unavailable"
const REJECT_MAP_FULL := "map_full"
const REJECT_TRANSFER_TOKEN := "bad_transfer_token"
const REJECT_ABORTED := "aborted"

## Combat state machine (plan Phase 5: idle -> windup -> release -> recovery -> idle).
enum CastState { IDLE = 0, WINDUP = 1, RELEASE = 2, RECOVERY = 3, STUNNED = 4, DEAD = 5 }

## Mob AI state (plan.md Phase 11), carried in a MOB entity's `state` byte so a
## client renders the authority's phase - anticipation, release, recovery, chase
## - instead of guessing it from movement. Values are append-only.
enum MobState {
	IDLE = 0,
	WANDER = 1,
	CHASE = 2,
	ATTACK = 3,
	ANTICIPATION = 4,
	RECOVERY = 5,
	STUNNED = 6,
	DEAD = 7,
	RETURN = 8,
}

## Entity kinds replicated to clients.
enum Kind { PLAYER = 1, MOB = 2, DUMMY = 3, MONOLITH = 4, LOOT = 5, NPC = 6 }

## Mount presentation phase (plan.md Phase 9). Carried in a PLAYER entity's
## existing `state` byte inside snapshots, so a remote client animates the same
## flight phase it would if it owned the body - the phase is decided here, from
## authoritative state, and never by the client that renders it. NONE means "not
## mounted"; every mounted player carries a phase >= SEATED.
enum MountPhase {
	NONE = 0,
	MOUNTING = 1,
	SEATED = 2,
	TAKEOFF = 3,
	ACCELERATE = 4,
	CRUISE = 5,
	BANK_L = 6,
	BANK_R = 7,
	CLIMB = 8,
	DIVE = 9,
	BRAKE = 10,
	LANDING = 11,
	DISMOUNT = 12,
}

## Pure derivation of the flight phase. `lateral` is the intent's left/right axis
## (+1 = right), `vertical` its climb axis (+1 = up), `speed_ratio` the horizontal
## speed over the mounted top speed, and `accel_ratio` its rate of change.
static func mount_phase_for(mounted: bool, lateral: float, vertical: float,
		speed_ratio: float, accel_ratio: float = 0.0) -> int:
	if not mounted:
		return MountPhase.NONE
	if vertical > 0.3:
		return MountPhase.CLIMB
	if vertical < -0.3:
		return MountPhase.DIVE
	if lateral < -0.4:
		return MountPhase.BANK_L
	if lateral > 0.4:
		return MountPhase.BANK_R
	if speed_ratio > 0.12 and accel_ratio < -1.5:
		return MountPhase.BRAKE
	if speed_ratio > 0.75:
		return MountPhase.CRUISE
	if speed_ratio > 0.2:
		return MountPhase.ACCELERATE
	return MountPhase.SEATED

## Per-entity presentation flags packed into one byte in snapshots.
const FLAG_DEAD := 1 << 0
const FLAG_MOUNTED := 1 << 1
const FLAG_CASTING := 1 << 2
const FLAG_STUNNED := 1 << 3
const FLAG_PROTECTED := 1 << 4
const FLAG_ENRAGED := 1 << 5
const FLAG_WARDED := 1 << 6
const FLAG_BOSS := 1 << 7

## Mob variants. Snapshots carry a variant byte instead of a scene path (28 bytes
## per entity total); both processes resolve it through this table, so a mob the
## server spawned appears on clients as the same creature.
const MOB_VARIANT_INFERI := 1
const MOB_VARIANT_ACROMANTULA := 2
const MOB_VARIANT_DARKSATCHER := 3

const MOB_SCENES := {
	MOB_VARIANT_INFERI: "res://scenes/entities/mobs/mob_inferi.tscn",
	MOB_VARIANT_ACROMANTULA: "res://scenes/entities/mobs/mob_acromantula.tscn",
	MOB_VARIANT_DARKSATCHER: "res://scenes/entities/mobs/mob_darksnatcher.tscn",
}

static func mob_variant(scene_path: String) -> int:
	for variant in MOB_SCENES.keys():
		if MOB_SCENES[variant] == scene_path:
			return int(variant)
	return MOB_VARIANT_INFERI

static func mob_scene(variant: int) -> String:
	return String(MOB_SCENES.get(variant, MOB_SCENES[MOB_VARIANT_INFERI]))

## Snapshot / event message names. Kept as constants so the contract extractor and
## both processes agree on a single spelling.
const MSG_JOIN := "join"
const MSG_JOIN_RESULT := "join_result"
const MSG_INPUT := "input_frame"
const MSG_CAST_REQUEST := "cast_request"
const MSG_CAST_RESULT := "cast_result"
const MSG_CAST_RELEASE := "cast_release"
const MSG_CAST_HIT := "cast_hit"
const MSG_MOUNT_REQUEST := "mount_request"
const MSG_TARGET_REQUEST := "target_request"
const MSG_INTERACT_REQUEST := "interact_request"
const MSG_PICKUP_REQUEST := "pickup_request"
const MSG_RESPAWN_REQUEST := "respawn_request"
## Map transfer exchange (plan.md Phase 8). request/ready/abort travel client ->
## server; granted/refused/committed/expired/map_state travel server -> client.
const MSG_TRANSFER_REQUEST := "transfer_request"
const MSG_TRANSFER_READY := "transfer_ready"
const MSG_TRANSFER_ABORT := "transfer_abort"
const MSG_TRANSFER_GRANTED := "transfer_granted"
const MSG_TRANSFER_REFUSED := "transfer_refused"
const MSG_TRANSFER_COMMITTED := "transfer_committed"
const MSG_TRANSFER_EXPIRED := "transfer_expired"
const MSG_MAP_STATE := "map_state"
const MSG_SNAPSHOT := "snapshot"
const MSG_DESPAWN := "despawn"
## Boss telegraph (plan.md Phase 11). Reliable, server -> client: the warning a
## player sees is driven by the authority's start/release ticks, and the damage
## is applied by the authority at the release tick.
const MSG_TELEGRAPH := "telegraph"
const MSG_TELEGRAPH_END := "telegraph_end"
const MSG_STATS := "stats"
const MSG_STAT_DELTA := "stat_delta"
const MSG_ENTITY_EVENT := "entity_event"
const MSG_CHAT := "chat"

## Stat delta keys carry the amount and the new absolute value so a client that
## missed an ordered delta still converges on the next full stats message.
const STAT_HP := "hp"
const STAT_MANA := "mana"
const STAT_EXP := "exp"
const STAT_LEVEL := "level"
const STAT_GALLEONS := "galleons"

## Result of validating a client request. `reason` is one of the REJECT_* strings.
static func accept() -> Dictionary:
	return {"ok": true, "reason": REJECT_OK}

static func reject(reason: String) -> Dictionary:
	return {"ok": false, "reason": reason}

static func version_string() -> String:
	return "hpmmo-proto/%d" % PROTOCOL_VERSION
